const cfg=window.ESLY_CONFIG,sb=supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY),$=s=>document.querySelector(s);
const iso=()=>{const d=new Date(Date.now()-new Date().getTimezoneOffset()*60000);return d.toISOString().slice(0,10)};
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const fmtDate=d=>new Date(`${d}T12:00:00`).toLocaleDateString("es-ES",{weekday:"long",day:"numeric",month:"long"});
const fmtTime=t=>{let [h,m]=String(t).slice(0,5).split(":").map(Number);return `${h%12||12}:${String(m).padStart(2,"0")} ${h>=12?"PM":"AM"}`};
const money=v=>v==null?"Consultar":`${Number(v).toLocaleString("es-ES")} ${cfg.BUSINESS.currency}`;
async function show(){const {data:{session}}=await sb.auth.getSession();if(session){$("#loginScreen").hidden=true;$("#adminApp").hidden=false;$("#agendaDate").value=iso();$("#blockDate").min=iso();loadDashboard()}}
$("#loginForm").onsubmit=async e=>{e.preventDefault();const {data,error}=await sb.auth.signInWithPassword({email:$("#email").value,password:$("#password").value});if(error){$("#loginMessage").textContent="Correo o contraseña incorrectos.";return}show()};
$("#logoutBtn").onclick=async()=>{await sb.auth.signOut();location.reload()};$("#refreshBtn").onclick=loadDashboard;$("#agendaDate").onchange=loadAppointments;$("#blockForm").onsubmit=createBlock;$("#serviceForm").onsubmit=createService;
async function loadDashboard(){await Promise.all([loadAppointments(),loadHours(),loadBlocks(),loadServices()]);const today=iso();const a=await sb.from("appointments").select("*",{count:"exact",head:true}).eq("date",today).eq("status","confirmed");const u=await sb.from("appointments").select("*",{count:"exact",head:true}).gte("date",today).eq("status","confirmed");$("#todayCount").textContent=a.count||0;$("#upcomingCount").textContent=u.count||0}
async function loadAppointments(){const date=$("#agendaDate").value;const {data,error}=await sb.from("appointments").select("*,services(name,duration_minutes)").eq("date",date).order("start_time");if(error)return $("#appointmentsList").innerHTML="<p>Error cargando reservas.</p>";if(!data?.length)return $("#appointmentsList").innerHTML=`<div class="empty">No hay reservas para ${fmtDate(date)}.</div>`;$("#appointmentsList").innerHTML=data.map(a=>`<article class="appointment"><div class="appt-time">${fmtTime(a.start_time)}<small>${a.services?.duration_minutes||""} min</small></div><div><b>${esc(a.customer_name)}</b><span>${esc(a.services?.name)} · ${esc(a.phone)}</span>${a.notes?`<small>Nota: ${esc(a.notes)}</small>`:""}</div><div><em class="badge ${a.status}">${esc(a.status)}</em>${a.status==="confirmed"?`<button data-cancel="${a.id}">Cancelar</button>`:""}</div></article>`).join("");document.querySelectorAll("[data-cancel]").forEach(b=>b.onclick=()=>cancelAppointment(b.dataset.cancel))}
async function cancelAppointment(id){if(!confirm("¿Cancelar esta reserva?"))return;await sb.from("appointments").update({status:"cancelled"}).eq("id",id);loadDashboard()}
async function loadHours(){const {data}=await sb.from("business_hours").select("*").order("day_of_week");const days=["Domingo","Lunes","Martes","Miércoles","Jueves","Viernes","Sábado"];$("#hoursList").innerHTML=(data||[]).map(h=>`<div class="rowline"><b>${days[h.day_of_week]}</b><span>${h.active?`${fmtTime(h.open_time)} - ${fmtTime(h.close_time)}`:"Cerrado"}</span><button data-hour="${h.id}" data-active="${h.active}">${h.active?"Desactivar":"Activar"}</button></div>`).join("");document.querySelectorAll("[data-hour]").forEach(b=>b.onclick=async()=>{await sb.from("business_hours").update({active:b.dataset.active!=="true"}).eq("id",b.dataset.hour);loadHours()})}
async function loadBlocks(){const {data}=await sb.from("blocked_slots").select("*").gte("date",iso()).order("date").order("start_time");$("#blocksList").innerHTML=data?.length?data.map(b=>`<div class="rowline"><div><b>${fmtDate(b.date)}</b><span>${fmtTime(b.start_time)} - ${fmtTime(b.end_time)} · ${esc(b.reason||"Sin motivo")}</span></div><button data-unblock="${b.id}">Eliminar</button></div>`).join(""):"<div class='empty'>No hay bloqueos futuros.</div>";document.querySelectorAll("[data-unblock]").forEach(b=>b.onclick=async()=>{await sb.from("blocked_slots").delete().eq("id",b.dataset.unblock);loadBlocks()})}
async function createBlock(e){e.preventDefault();const {error}=await sb.from("blocked_slots").insert({date:$("#blockDate").value,start_time:$("#blockStart").value,end_time:$("#blockEnd").value,reason:$("#blockReason").value.trim()});if(error)return alert(error.message);e.target.reset();$("#blockDate").min=iso();loadBlocks()}
async function loadServices(){const {data}=await sb.from("services").select("*").order("sort_order");$("#serviceCount").textContent=(data||[]).filter(s=>s.active).length;$("#servicesAdminList").innerHTML=(data||[]).map(s=>`<div class="rowline"><div><b>${esc(s.name)}</b><span>${s.duration_minutes} min · ${money(s.price)}</span></div><button data-service="${s.id}" data-active="${s.active}">${s.active?"Desactivar":"Activar"}</button></div>`).join("");document.querySelectorAll("[data-service]").forEach(b=>b.onclick=async()=>{await sb.from("services").update({active:b.dataset.active!=="true"}).eq("id",b.dataset.service);loadServices()})}
async function createService(e){e.preventDefault();const {error}=await sb.from("services").insert({name:$("#newServiceName").value.trim(),price:Number($("#newServicePrice").value)||null,duration_minutes:Number($("#newServiceDuration").value),description:$("#newServiceDescription").value.trim(),active:true});if(error)return alert(error.message);e.target.reset();$("#newServiceDuration").value=60;loadServices()}show();