create extension if not exists pgcrypto;
create table if not exists public.services(id uuid primary key default gen_random_uuid(),name text not null,description text,price numeric(10,2),duration_minutes integer not null default 60 check(duration_minutes between 15 and 480),active boolean not null default true,sort_order integer not null default 0,created_at timestamptz not null default now());
create table if not exists public.business_hours(id uuid primary key default gen_random_uuid(),day_of_week integer not null unique check(day_of_week between 0 and 6),open_time time not null default '09:00',close_time time not null default '17:00',active boolean not null default true);
create table if not exists public.blocked_slots(id uuid primary key default gen_random_uuid(),date date not null,start_time time not null,end_time time not null,reason text,created_at timestamptz not null default now(),check(end_time>start_time));
create table if not exists public.appointments(id uuid primary key default gen_random_uuid(),customer_name text not null,phone text not null,service_id uuid not null references public.services(id),date date not null,start_time time not null,end_time time not null,status text not null default 'confirmed' check(status in('confirmed','cancelled')),notes text,created_at timestamptz not null default now(),check(end_time>start_time));
create index if not exists appointments_date_idx on public.appointments(date,start_time);
alter table public.services enable row level security; alter table public.business_hours enable row level security; alter table public.blocked_slots enable row level security; alter table public.appointments enable row level security;
drop policy if exists "public services" on public.services; create policy "public services" on public.services for select to anon,authenticated using(active=true);
drop policy if exists "public hours" on public.business_hours; create policy "public hours" on public.business_hours for select to anon,authenticated using(true);
drop policy if exists "public blocks" on public.blocked_slots; create policy "public blocks" on public.blocked_slots for select to anon,authenticated using(true);
drop policy if exists "admin services" on public.services; create policy "admin services" on public.services for all to authenticated using(true) with check(true);
drop policy if exists "admin hours" on public.business_hours; create policy "admin hours" on public.business_hours for all to authenticated using(true) with check(true);
drop policy if exists "admin blocks" on public.blocked_slots; create policy "admin blocks" on public.blocked_slots for all to authenticated using(true) with check(true);
drop policy if exists "admin appointments read" on public.appointments; create policy "admin appointments read" on public.appointments for select to authenticated using(true);
drop policy if exists "admin appointments update" on public.appointments; create policy "admin appointments update" on public.appointments for update to authenticated using(true) with check(true);
insert into public.business_hours(day_of_week,open_time,close_time,active) values(0,'09:00','17:00',false),(1,'09:00','17:00',true),(2,'09:00','17:00',true),(3,'09:00','17:00',true),(4,'09:00','17:00',true),(5,'09:00','17:00',true),(6,'09:00','14:00',true) on conflict(day_of_week) do nothing;
insert into public.services(name,description,price,duration_minutes,sort_order) values('Manicura','Cuidado, limpieza y acabado impecable.',null,60,1),('Manicura Gel','Color, brillo y mayor duración.',null,90,2),('Pedicura','Cuidado completo para tus pies.',null,75,3),('Uñas Acrílicas','Construcción y diseño personalizado.',null,120,4),('Soft Gel','Extensión ligera con acabado elegante.',null,120,5),('Nail Art','Diseños personalizados.',null,30,6) on conflict do nothing;
create or replace function public.get_available_slots(p_date date,p_service_id uuid) returns table(start_time time,end_time time,display_time text) language plpgsql security definer set search_path=public as $$
declare d integer;o time;c time;dur integer;s time;e time;
begin select extract(dow from p_date)::integer into d;select open_time,close_time into o,c from business_hours where day_of_week=d and active=true;if o is null then return;end if;select duration_minutes into dur from services where id=p_service_id and active=true;if dur is null then return;end if;s=o;while s+make_interval(mins=>dur)<=c loop e=s+make_interval(mins=>dur);if not exists(select 1 from appointments a where a.date=p_date and a.status='confirmed' and a.start_time<e and a.end_time>s) and not exists(select 1 from blocked_slots b where b.date=p_date and b.start_time<e and b.end_time>s) then start_time=s;end_time=e;display_time=to_char(s,'HH12:MI AM');return next;end if;s=s+interval '30 minutes';end loop;end;$$;
grant execute on function public.get_available_slots(date,uuid) to anon,authenticated;
create or replace function public.create_appointment(p_customer_name text,p_phone text,p_service_id uuid,p_date date,p_start_time time,p_notes text default null) returns table(id uuid,end_time time) language plpgsql security definer set search_path=public as $$
declare dur integer;e time;d integer;o time;c time;
begin if length(trim(p_customer_name))<2 then raise exception 'Nombre inválido';end if;if length(trim(p_phone))<5 then raise exception 'Teléfono inválido';end if;select duration_minutes into dur from services where id=p_service_id and active=true;if dur is null then raise exception 'Servicio no disponible';end if;select extract(dow from p_date)::integer into d;select open_time,close_time into o,c from business_hours where day_of_week=d and active=true;if o is null then raise exception 'DIA_CERRADO';end if;e=p_start_time+make_interval(mins=>dur);if p_start_time<o or e>c then raise exception 'HORARIO_INVALIDO';end if;if exists(select 1 from blocked_slots b where b.date=p_date and b.start_time<e and b.end_time>p_start_time) then raise exception 'SLOT_UNAVAILABLE';end if;if exists(select 1 from appointments a where a.date=p_date and a.status='confirmed' and a.start_time<e and a.end_time>p_start_time) then raise exception 'SLOT_UNAVAILABLE';end if;insert into appointments(customer_name,phone,service_id,date,start_time,end_time,notes) values(trim(p_customer_name),trim(p_phone),p_service_id,p_date,p_start_time,e,nullif(trim(p_notes),'')) returning appointments.id,appointments.end_time into id,end_time;return next;end;$$;
grant execute on function public.create_appointment(text,text,uuid,date,time,text) to anon,authenticated;
revoke all on public.appointments from anon;
grant select on public.services,public.business_hours,public.blocked_slots to anon;
grant select,insert,update,delete on public.services,public.business_hours,public.blocked_slots,public.appointments to authenticated;
